-- H2（MySQL 模式）与 ws_host_whitelist 纳管查询集成测试
CREATE TABLE IF NOT EXISTS ws_host_whitelist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host_id VARCHAR(50) NOT NULL,
  host_name VARCHAR(100),
  owner_name VARCHAR(50),
  owner_contact VARCHAR(100),
  is_team TINYINT NOT NULL DEFAULT 0,
  team_name VARCHAR(100),
  allowed_ips VARCHAR(500),
  status TINYINT NOT NULL DEFAULT 1,
  expire_time TIMESTAMP,
  remark VARCHAR(255),
  del_flag TINYINT NOT NULL DEFAULT 0,
  create_by VARCHAR(64),
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time TIMESTAMP,
  host_type VARCHAR(20) DEFAULT 'engine',
  health_check_url VARCHAR(255),
  online_status VARCHAR(20) DEFAULT 'offline',
  CONSTRAINT uk_host_id UNIQUE (host_id)
);
